---
- name: install nginx for centos6
  include: nginx_for_Centos6.yml
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: install nginx for centos7
  include: nginx_for_Centos7.yml
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"