---
- name: install nginx 
  yum: name=nginx state=present
  ignore_errors: yes

- name: copy nginx template
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf 

# - name : edit nginx conf
#   lineinfile: dest=/etc/nginx/nginx.conf regexp="^default_type" line=""
#   when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name : add rule to iptables
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ nginx_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ nginx_port }} -j  ACCEPT"
  notify: restart iptables

- name: start nginx and permanent
  service: name=nginx state=restarted enabled=yes
  ignore_errors: yes
