---
- name: install mysql for centos6
  include: mysql_for_Centos6.yml
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: install mysql for centos7
  include: mysql_for_Centos7.yml
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
