---
- name: Install common for centos6
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
  ignore_errors: yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: Install common for centos7
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
    - firewalld
  ignore_errors: yes  
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"



