---
- name: install php for Centos6
  include: php_for_Centos6.yml
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: install php for Centos7
  include: php_for_Centos7.yml
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"