---
- name: Install php etc
  yum: name={{ item }} state=present
  with_items:
   - php
   - php-mysql
   - git
   - php-fpm 

- name: start php-fpm permantent
  service: name=php-fpm state=restarted enabled=yes
  ignore_errors: yes

- name: copy php file to test if it's installed
  template: src=index.php.j2 dest=/usr/share/nginx/html/index.php