---
- name: Install php etc
  yum: name={{ item }} state=present
  with_items:
   - php
   - php-mysql
   - git
   - php-fpm 

- name: creat conf file for php-fpm
  template:
    src: php-fpm.conf 
    dest: /etc/nginx/default.d/

- name: start php-fpm permantent
  service: name=php-fpm state=restarted enabled=yes
  ignore_errors: yes

- name: restart nginx
  service: name=nginx state=restarted   

- name: copy php file to test if it's installed
  template: src=index.php.j2 dest=/usr/share/nginx/html/index.php